#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

#define LV_COLOR_DEPTH 16
#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (64U * 1024U)
#define LV_TICK_CUSTOM 0

#define LV_USE_PERF_MONITOR 0
#define LV_USE_MEM_MONITOR 0
#define LV_USE_ASSERT_NULL 0
#define LV_USE_ASSERT_MALLOC 0
#define LV_USE_ASSERT_STYLE 0

#define LV_USE_LABEL 1
#define LV_USE_BAR 1
#define LV_USE_LINE 1
#define LV_USE_OBJ 1
#define LV_USE_ANIMATION 1

#define LV_USE_LOG 0

#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_22 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_28 1
#define LV_FONT_MONTSERRAT_32 1
#define LV_FONT_MONTSERRAT_36 1
#define LV_FONT_MONTSERRAT_40 1
#define LV_FONT_SIMSUN_16_CJK 0
#define LV_FONT_DEFAULT &lv_font_montserrat_14

#define LV_USE_THEME_DEFAULT 0
#define LV_USE_FLEX 1
#define LV_USE_GRID 1

#define LV_USE_GPU 0
#define LV_USE_DRAW_MASKS 1
#define LV_USE_IMG 1
#define LV_USE_ARC 1
#define LV_USE_BTN 1
#define LV_USE_SLIDER 0
#define LV_USE_CHART 0
#define LV_USE_TABLE 0

#endif
