[env:waveshare_rlcd_42]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
upload_speed = 115200
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DDISPLAY_WIDTH=400
    -DDISPLAY_HEIGHT=300
    -DPIN_DC=5
    -DPIN_CS=40
    -DPIN_SCLK=11
    -DPIN_SDIN=12
    -DPIN_RST=41

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    h2zero/NimBLE-Arduino@^2.5.0
    https://github.com/FT-tele/ST7305_MonoTFT_Arduino_Library.git
